 -- Errors -- 
2019-02-25 11:37:59 Error Create Table:CREATE TABLE LYY.CLOB1(ID NUMERIC(126,0),TXT TEXT);
错误: 关系 "clob1" 已经存在
2019-02-25 11:37:59 Error Migrate Defination for Table:LYY.CLOB1
org.postgresql.util.PSQLException: 错误: 关系 "clob1" 已经存在
2019-02-25 11:37:59 Error Create Table:CREATE TABLE LYY.CLOB2(ID NUMERIC(126,0),TXT TEXT,IMAGE BYTEA);
错误: 关系 "clob2" 已经存在
2019-02-25 11:37:59 Error Migrate Defination for Table:LYY.CLOB2
org.postgresql.util.PSQLException: 错误: 关系 "clob2" 已经存在
2019-02-25 11:38:00 Error Create Table:CREATE TABLE LYY.CLOB3(ID NUMERIC(126,0),TXT TEXT);
错误: 关系 "clob3" 已经存在
2019-02-25 11:38:00 Error Migrate Defination for Table:LYY.CLOB3
org.postgresql.util.PSQLException: 错误: 关系 "clob3" 已经存在
